# Generated by Django 3.2.9 on 2021-11-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SportBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_branch', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outfit_name', models.CharField(max_length=128)),
                ('size', models.CharField(choices=[('XL', 'XL'), ('L', 'L'), ('M', 'M'), ('S', 'S')], max_length=128, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unisex', 'Unisex')], max_length=128, null=True)),
                ('description', models.TextField(max_length=200, null=True)),
                ('price', models.FloatField(null=True)),
                ('availability', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=128, null=True)),
                ('sport_branch', models.ManyToManyField(to='webshop.SportBranch')),
            ],
        ),
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gear_name', models.CharField(max_length=128, null=True)),
                ('availability', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=128, null=True)),
                ('description', models.TextField(max_length=200, null=True)),
                ('rent', models.CharField(choices=[('For Rent', 'For Rent'), ('Not For Rent', 'Not For Rent')], max_length=128, null=True)),
                ('rent_price', models.FloatField(null=True)),
                ('price', models.FloatField(null=True)),
                ('sport_branch', models.ManyToManyField(to='webshop.SportBranch')),
            ],
        ),
    ]
